=== Khushi130404/Web-Lab/XML/message.dtd
<!ELEMENT message(letter|email)>
<!ELEMENT letter(letterHead,letterBody)>
<!ELEMENT letterHead(name,address,date?,subject?)>
<!ELEMENT letterBody(text+,writer)>
<!ELEMENT email(head|body)>
<!ELEMENT head(to+,from,date?,subject?)>
<!ELEMENT body(text+)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT address(#PCDATA)>
<!ELEMENT date(#PCDATA)>
<!ELEMENT subject(#PCDATA)>
<!ELEMENT text(#PCDATA)>
<!ELEMENT writer(#PCDATA)>
<!ELEMENT to(#PCDATA)>
<!ELEMENT from(#PCDATA)>
<!ATTLIST letter reply (yes|no) "no">
<!ATTLIST email reply (yes|no) "no">

=== Khushi130404/Web-Lab/XML/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE message SYSTEM "message.dtd">
<message>
    <letter reply="yes">
        <letterHead>
            <name>Khushi</name>
            <address>Vadodara</address>
            <date>13-04-2024</date>
            <subject>A letter</subject>
        </letterHead>
        <letterBody>
            <text>This is a letter body</text>
            <writer>Krutika</writer>
        <letterBody>
    </letter>
</message>
